<template>
  <div class="quick-add-form d-flex flex-column ga-4">
    <!-- Provider 选择（模板化添加：选 provider + 输 key，系统自动判别 plan/baseURL） -->
    <div class="d-flex align-center ga-2">
      <v-icon color="primary" size="20">mdi-shape-outline</v-icon>
      <div class="text-caption text-medium-emphasis flex-shrink-0">
        {{ t('autopilot.quickAdd.provider.label') }}
      </div>
      <v-spacer />
      <v-select
        v-model="displayProviderId"
        :items="providerItems"
        item-title="title"
        item-value="value"
        variant="outlined"
        density="compact"
        hide-details
        :disabled="providerTemplatesLoading"
        :loading="providerTemplatesLoading"
        :menu-props="{ contentClass: 'upstream-select-menu' }"
        class="provider-select"
        @update:model-value="clearSubmitError"
      />
    </div>

    <!-- new-api 通用接入：不额外弹窗，表单体就地切换为订阅接入表单（与订阅中心同一表单）；
         经顶部服务商下拉或 Esc 退回常规快速添加 -->
    <template v-if="isNewApiMode">
      <NewApiSubscriptionForm ref="newApiFormRef" @created="onNewApiCreated" @error="onNewApiError" />
      <v-alert v-if="submitError" color="error" variant="tonal" density="comfortable" icon="mdi-alert-circle-outline">
        {{ submitError }}
      </v-alert>
    </template>

    <template v-else>
    <!-- Provider 说明 -->
    <v-alert
      v-if="isProviderMode && selectedProvider?.description"
      color="primary"
      variant="tonal"
      density="comfortable"
      icon="mdi-information"
    >
      {{ selectedProvider.description }}
    </v-alert>

    <!-- Base URL 输入（仅显式选择 provider 时隐藏；自动识别时保留，允许第三方 URL 覆盖 Key 推断） -->
    <div v-if="!isExplicitProviderMode">
      <div class="d-flex align-center justify-space-between mb-2">
        <div class="d-flex align-center ga-2">
          <v-icon size="16" color="medium-emphasis">mdi-web</v-icon>
          <span class="text-body-2 font-weight-medium">{{ t('addChannel.baseUrl') }}</span>
        </div>
        <v-btn size="small" variant="text" color="primary" @click="addBaseUrl">
          <v-icon start size="small">mdi-plus</v-icon>
          {{ t('autopilot.quickAdd.addUrl') }}
        </v-btn>
      </div>
      <div class="d-flex flex-column ga-2">
        <div v-for="(_, idx) in baseUrls" :key="'url-' + idx" class="d-flex align-start ga-2">
          <div class="base-url-field">
            <v-text-field
              v-model="baseUrls[idx]"
              :placeholder="t('addChannel.baseUrl') + ' ' + (idx + 1)"
              variant="outlined"
              density="compact"
              hide-details
            />
            <div
              v-if="recognizedBaseUrls[idx]"
              class="recognized-base-url d-flex align-start ga-1 mt-1 text-caption text-medium-emphasis"
            >
              <v-icon size="14" color="success" class="mt-1">mdi-arrow-right</v-icon>
              <span>{{ t('autopilot.quickAdd.recognizedBaseUrl', { url: recognizedBaseUrls[idx] }) }}</span>
            </div>
          </div>
          <v-btn
            v-if="baseUrls.length > 1"
            size="small"
            icon
            variant="text"
            color="error"
            class="mt-1"
            @click="removeBaseUrl(idx)"
          >
            <v-icon size="small">mdi-close</v-icon>
          </v-btn>
        </div>
      </div>
    </div>

    <!-- 代理 URL（可选）：境外上游直连不可达时经代理发现与访问 -->
    <div v-if="!isExplicitProviderMode">
      <v-text-field
        v-model="proxyUrl"
        :label="t('addChannel.proxyUrlLabel')"
        :placeholder="t('addChannel.proxyUrlPlaceholder')"
        :hint="t('addChannel.proxyUrlHint')"
        persistent-hint
        variant="outlined"
        density="compact"
        prepend-inner-icon="mdi-vpn"
        class="mt-1"
      />
      <v-switch
        v-model="proxyPreferDirect"
        :label="t('addChannel.proxyPreferDirectLabel')"
        :hint="t('addChannel.proxyPreferDirectHint')"
        persistent-hint
        color="primary"
        density="compact"
        :disabled="!proxyUrl.trim()"
      />
    </div>

    <div
      v-if="generatedChannelName"
      class="channel-name-preview d-flex align-center ga-3 pa-3 rounded-lg"
    >
      <v-icon color="primary" size="20">mdi-tag</v-icon>
      <div class="flex-grow-1">
        <div class="text-caption text-medium-emphasis">{{ t('addChannel.channelName') }}</div>
        <div class="text-body-2 font-weight-bold text-primary">{{ generatedChannelName }}</div>
      </div>
      <v-chip size="x-small" color="primary" variant="tonal">
        {{ t('common.autoGenerated') }}
      </v-chip>
    </div>

    <v-alert
      v-if="duplicateChannel"
      color="info"
      variant="tonal"
      density="comfortable"
      icon="mdi-content-duplicate"
    >
      {{ t('autopilot.quickAdd.alreadyAdded', { name: duplicateChannel.channel.logicalName || duplicateChannel.channel.name }) }}
    </v-alert>

    <!-- API Key 输入 -->
    <div>
      <div class="d-flex align-center justify-space-between mb-2">
        <div class="d-flex align-center ga-2">
          <v-icon size="16" color="medium-emphasis">mdi-key</v-icon>
          <span class="text-body-2 font-weight-medium">{{ t('addChannel.apiKeys') }}</span>
        </div>
        <v-btn size="small" variant="text" color="primary" @click="addApiKey">
          <v-icon start size="small">mdi-plus</v-icon>
          {{ t('autopilot.quickAdd.addKey') }}
        </v-btn>
      </div>
      <div class="d-flex flex-column ga-2">
        <div v-for="(key, idx) in apiKeys" :key="'key-' + idx" class="d-flex align-center ga-2">
          <v-text-field
            v-model="apiKeys[idx]"
            :placeholder="`${t('app.dialog.apiKeyPlaceholder')} ${idx + 1}`"
            variant="outlined"
            density="compact"
            hide-details
            :type="showKeys[idx] ? 'text' : 'password'"
            class="flex-grow-1"
          >
            <template #append-inner>
              <v-icon size="small" class="cursor-pointer" @click="toggleKeyVisibility(idx)">
                {{ showKeys[idx] ? 'mdi-eye-off' : 'mdi-eye' }}
              </v-icon>
            </template>
          </v-text-field>
          <v-btn v-if="apiKeys.length > 1" size="small" icon variant="text" color="error" @click="removeApiKey(idx)">
            <v-icon size="small">mdi-close</v-icon>
          </v-btn>
        </div>
      </div>
    </div>

    <!-- 故障转移位置（与 desktop 一致：API Keys 下方开关） -->
    <div
      class="d-flex align-center ga-3 pa-3 rounded-lg placement-card"
      :class="{ 'placement-card-disabled': submitting }"
      @click="togglePlacement"
    >
      <v-icon color="primary" size="20">mdi-playlist-plus</v-icon>
      <div class="flex-grow-1">
        <div class="text-body-2 font-weight-medium">{{ t('addChannel.placementBack') }}</div>
      </div>
      <v-switch
        :model-value="placement === 'back'"
        readonly
        hide-details
        density="compact"
        color="primary"
        class="flex-grow-0 placement-switch"
      />
    </div>

    <!-- 提交错误（provider 模式 key 无效等） -->
    <v-alert v-if="submitError" color="error" variant="tonal" density="comfortable" icon="mdi-alert-circle-outline">
      {{ submitError }}
    </v-alert>

    <!-- 创建状态面板；发现任务在创建成功后转入后台 -->
    <v-card v-if="submitting" variant="outlined" class="discovery-card" rounded="lg">
      <v-card-text class="pa-4">
        <div class="d-flex align-center ga-3">
          <v-progress-circular indeterminate size="20" width="2" color="primary" />
          <span class="text-body-2 font-weight-medium">{{ t('autopilot.quickAdd.discovering') }}</span>
        </div>
      </v-card-text>
    </v-card>

    </template>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useI18n } from '../i18n'
import type { Channel } from '../services/api'
import {
  autoAddChannel,
  discoverFast,
  extractAutoAddErrorMessage,
  getProviderTemplates
} from '../services/autopilot-api'
import type { ProviderTemplate } from '../services/autopilot-api'
import type { NewApiProvisionResponse } from '../services/api-types'
import NewApiSubscriptionForm from './NewApiSubscriptionForm.vue'
import {
  buildQuickAddChannelName,
  findExistingQuickAddChannel,
  inferQuickAddProviderId,
  normalizeQuickAddApiKeys,
  normalizeQuickAddBaseUrls,
  recognizeQuickAddBaseUrl
} from '../utils/quickAddChannel'

type ChannelType = 'messages' | 'chat' | 'responses' | 'gemini' | 'images' | 'vectors'

interface Props {
  channelType: ChannelType
  existingChannels?: Channel[]
  /** 新渠道故障转移位置：front（首位）| back（末尾，默认） */
  placement?: 'front' | 'back'
}

const props = withDefaults(defineProps<Props>(), {
  existingChannels: () => [],
  placement: 'back'
})

const emit = defineEmits<{
  added: [channelId: number]
  close: []
  'update:placement': [value: 'front' | 'back']
}>()

const { t } = useI18n()

// ---- 表单状态 ----
const baseUrls = ref<string[]>([''])
const apiKeys = ref<string[]>([''])
const proxyUrl = ref('')
const proxyPreferDirect = ref(false)
const showKeys = ref<boolean[]>([false])
const submitting = ref(false)
const submitError = ref('')

// ---- Provider 模板状态 ----
// '' 表示自定义模式（手填 baseURL）；非空表示选中某已知 provider（模板化添加）。
// 模板加载完成后默认选中首个服务商（赞助商序第一位：火山）。
const providerId = ref('')
const providerTemplates = ref<ProviderTemplate[]>([])
const providerTemplatesLoading = ref(true)

// ---- Provider 模板计算属性 ----
// 赞助商展示顺序与订阅中心/README 保持一致，排在服务商列表最前（无模板的赞助商自然跳过）
const SPONSOR_PROVIDER_ORDER = ['volcengine', 'compshare', 'runapi']

// 不按 channelKind 过滤：所有 provider 都对用户可见（与订阅中心对齐）；
// 选中后由 handleSubmit 用 provider.channelKind 提交，保证多渠道自动建全
const availableProviders = computed(() => {
  const sponsorRank = (p: ProviderTemplate) => {
    const idx = SPONSOR_PROVIDER_ORDER.indexOf(p.providerId)
    return idx === -1 ? SPONSOR_PROVIDER_ORDER.length : idx
  }
  return [...providerTemplates.value].sort((a, b) => sponsorRank(a) - sponsorRank(b))
})

// 默认选中的服务商：当前渠道类型下排序后的第一个（即火山）；无可用模板时回退自定义模式
const defaultProviderId = computed(() => availableProviders.value[0]?.providerId ?? '')

// new-api 通用接入是独立流程（与订阅中心一致的两步接入表单）：选中后表单体就地切换，不占用 provider 模板状态
const NEW_API_PROVIDER_VALUE = '__new_api__'

// 选择项：赞助商/已知 provider 在前，其次 new-api 通用接入，「自定义」（value=''，手填地址）固定在最末
const providerItems = computed(() => [
  ...availableProviders.value.map(p => ({ title: p.displayName, value: p.providerId })),
  { title: t('autopilot.quickAdd.provider.newApi'), value: NEW_API_PROVIDER_VALUE },
  { title: t('autopilot.quickAdd.provider.custom'), value: '' }
])

const inferredProviderId = computed(() =>
  inferQuickAddProviderId(availableProviders.value, baseUrls.value, apiKeys.value)
)
const effectiveProviderId = computed(() => providerId.value || inferredProviderId.value)
const displayProviderId = computed({
  get: () => effectiveProviderId.value,
  set: value => {
    providerId.value = value ?? ''
  }
})

// ---- new-api 通用接入（内嵌） ----
const newApiFormRef = ref<InstanceType<typeof NewApiSubscriptionForm> | null>(null)
const isNewApiMode = computed(() => providerId.value === NEW_API_PROVIDER_VALUE)

function onNewApiCreated(result: NewApiProvisionResponse) {
  emit('added', result.channelIndex)
}

function onNewApiError(message: string) {
  submitError.value = message
}

/** Esc 栈顶语义：new-api 模式下先退回默认服务商；返回是否消费了本次 Esc */
function exitNewApiMode(): boolean {
  if (!isNewApiMode.value) return false
  providerId.value = defaultProviderId.value
  submitError.value = ''
  return true
}
const selectedProvider = computed(() => availableProviders.value.find(p => p.providerId === effectiveProviderId.value))

const isExplicitProviderMode = computed(() => providerId.value !== '')
const isProviderMode = computed(() => effectiveProviderId.value !== '')
const recognizedBaseUrls = computed(() => baseUrls.value.map(url => recognizeQuickAddBaseUrl(url, props.channelType)))
const normalizedBaseUrls = computed(() => normalizeQuickAddBaseUrls(baseUrls.value, props.channelType))
const generatedChannelName = computed(() => {
  const baseUrl = normalizedBaseUrls.value[0]
  return baseUrl ? buildQuickAddChannelName(baseUrl, 'preview') : ''
})
const duplicateChannel = computed(() =>
  isProviderMode.value ? null : findExistingQuickAddChannel(normalizedBaseUrls.value, props.existingChannels)
)

const isFormValid = computed(() => {
  const hasKey = apiKeys.value.some(k => k.trim() !== '')
  // provider 模式：baseURL 由后端判定，只需 key
  if (isProviderMode.value) return hasKey
  return normalizedBaseUrls.value.length > 0 && hasKey
})

// ---- 方法 ----
function clearSubmitError() {
  submitError.value = ''
}

// 切换故障转移位置（back=追加到末尾 / front=置顶优先），提交中禁止切换
function togglePlacement() {
  if (submitting.value) return
  emit('update:placement', props.placement === 'back' ? 'front' : 'back')
}

async function loadProviderTemplates() {
  providerTemplatesLoading.value = true
  try {
    providerTemplates.value = await getProviderTemplates()
  } catch {
    try {
      // 预取可能因瞬时认证状态失败；当前表单内受控重试一次。
      providerTemplates.value = await getProviderTemplates()
    } catch (err) {
      console.error('[QuickAdd-Provider] 加载 provider 模板失败:', err)
      providerTemplates.value = []
    }
  } finally {
    providerTemplatesLoading.value = false
    // 模板就绪后应用默认服务商（赞助商序第一位：火山）；用户已手动选择时不覆盖
    if (providerId.value === '') {
      providerId.value = defaultProviderId.value
    }
  }
}

function addBaseUrl() {
  baseUrls.value.push('')
}

function removeBaseUrl(idx: number) {
  baseUrls.value.splice(idx, 1)
}

function addApiKey() {
  apiKeys.value.push('')
  showKeys.value.push(false)
}

function removeApiKey(idx: number) {
  apiKeys.value.splice(idx, 1)
  showKeys.value.splice(idx, 1)
}

function toggleKeyVisibility(idx: number) {
  showKeys.value[idx] = !showKeys.value[idx]
}

function getFilteredBaseUrls(): string[] {
  return [...normalizedBaseUrls.value]
}

function getFilteredApiKeys(): string[] {
  return normalizeQuickAddApiKeys(apiKeys.value)
}

function generateRandomSuffix(length = 6): string {
  const chars = 'abcdefghijklmnopqrstuvwxyz0123456789'
  let result = ''
  for (let i = 0; i < length; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length))
  }
  return result
}

function getGeneratedName(): string {
  return generatedChannelName.value || buildQuickAddChannelName('', generateRandomSuffix())
}

async function discoverCustomRoutes(baseUrls: string[], apiKeys: string[]) {
  const discovery = await discoverFast(props.channelType, baseUrls, apiKeys, {
    proxyUrl: proxyUrl.value.trim() || undefined,
    proxyPreferDirect: proxyPreferDirect.value || undefined
  })
  if (!discovery) {
    throw new Error(t('autopilot.quickAdd.discoveryFailed'))
  }
  return discovery
}

async function handleSubmit() {
  // new-api 模式：主操作由内嵌表单按当前步骤决定（未验证→验证，已验证→接入）
  if (isNewApiMode.value) {
    newApiFormRef.value?.requestPrimaryAction()
    return
  }
  if (!isFormValid.value || submitting.value) return

  submitting.value = true
  submitError.value = ''

  try {
    const filteredBaseUrls = getFilteredBaseUrls()
    const filteredApiKeys = getFilteredApiKeys()
    apiKeys.value = [...filteredApiKeys]
    showKeys.value = filteredApiKeys.map(() => false)
    const routeDiscovery = isProviderMode.value ? null : await discoverCustomRoutes(filteredBaseUrls, filteredApiKeys)
    // provider 模式：用 provider.channelKind 提交（自动创建该 provider 支持的全部渠道），
    // 避免当前 tab 与 provider 支持范围不匹配导致 400
    const targetChannelType = isProviderMode.value
      ? ((selectedProvider.value?.channelKind as ChannelType | undefined) ?? props.channelType)
      : (routeDiscovery?.primaryKind ?? props.channelType)
    const result = await autoAddChannel(
      targetChannelType,
      isProviderMode.value
        ? {
            providerId: effectiveProviderId.value,
            apiKeys: filteredApiKeys,
            placement: props.placement
          }
        : {
            name: getGeneratedName(),
            baseUrls: filteredBaseUrls,
            apiKeys: filteredApiKeys,
            routes: routeDiscovery?.routes,
            rateLimitHint: routeDiscovery?.rateLimitHint,
            proxyUrl: proxyUrl.value.trim() || undefined,
            proxyPreferDirect: proxyPreferDirect.value || undefined,
            placement: props.placement
          }
    )

    const currentChannel = result.channels?.find(ch => ch.channelKind === targetChannelType)
    const currentIndex = currentChannel?.index ?? result.index
    submitting.value = false
    emit('added', currentIndex)
  } catch (err) {
    submitting.value = false
    // provider 模式下后端会对无效 key 返回 400（含明确原因），提取给用户
    submitError.value = extractAutoAddErrorMessage(err)
    console.error('[QuickAdd-Submit] 自动添加渠道失败:', err)
  }
}

function resetForm() {
  providerId.value = defaultProviderId.value
  baseUrls.value = ['']
  apiKeys.value = ['']
  proxyUrl.value = ''
  proxyPreferDirect.value = false
  showKeys.value = [false]
  submitting.value = false
  submitError.value = ''
}

// ---- 生命周期 ----
onMounted(() => {
  loadProviderTemplates()
})

// 暴露给父组件
defineExpose({ handleSubmit, resetForm, isFormValid, submitting, isNewApiMode, exitNewApiMode })
</script>

<style scoped>
.quick-add-form {
  min-height: 0;
}

.provider-select {
  min-width: 200px;
  max-width: 260px;
}

.base-url-field {
  flex: 1 1 auto;
  min-width: 0;
}

.recognized-base-url {
  overflow-wrap: anywhere;
}

.channel-name-preview {
  background: rgba(var(--v-theme-primary), 0.06);
  border: 1px solid rgba(var(--v-theme-primary), 0.16);
}

.discovery-card {
  border-color: rgba(var(--v-theme-outline), 0.32);
}

.placement-card {
  border: 1px solid rgba(var(--v-theme-outline), 0.32);
  cursor: pointer;
  transition:
    border-color 0.15s ease,
    background-color 0.15s ease;
}

.placement-card:hover {
  border-color: rgba(var(--v-theme-primary), 0.4);
  background-color: rgba(var(--v-theme-primary), 0.05);
}

.placement-card-disabled {
  cursor: default;
  opacity: 0.6;
  pointer-events: none;
}

.placement-switch {
  pointer-events: none;
}
</style>
