package channelpreset

// Code generated by scripts/generate-channel-presets.mjs; DO NOT EDIT.

func generatedOpenAIChatTargetConfigs() map[string]channelTargetConfig {
	return map[string]channelTargetConfig{
		"deepseek":     channelTargetConfig{ReasoningParamStyle: "reasoning", NoVision: true},
		"mimo":         channelTargetConfig{ReasoningParamStyle: "thinking", NoVisionModels: []string{"mimo-v2.5-pro"}, VisionFallbackModel: "mimo-v2.5", RateLimitRPM: 80},
		"compshare":    channelTargetConfig{ReasoningParamStyle: "reasoning", NoVisionModels: []string{"glm-5.2", "deepseek-v4-flash"}, VisionFallbackModel: "MiniMax-M2.7"},
		"runapi":       channelTargetConfig{},
		"unity2":       channelTargetConfig{},
		"openrouter":   channelTargetConfig{},
		"modelscope":   channelTargetConfig{NormalizeNonstandardChatRoles: true},
		"minimax":      channelTargetConfig{},
		"dashscope":    channelTargetConfig{},
		"opencode-zen": channelTargetConfig{},
		"opencode-go":  channelTargetConfig{},
		"volc-ark":     channelTargetConfig{NormalizeNonstandardChatRoles: true},
		"qianfan":      channelTargetConfig{NormalizeNonstandardChatRoles: true},
		"xfyun":        channelTargetConfig{ModelMapping: map[string]string{"codex": "astron-code-latest", "gpt": "astron-code-latest", "mini": "astron-code-latest"}, NormalizeNonstandardChatRoles: true},
	}
}
