package channelpreset

// Code generated by scripts/generate-channel-presets.mjs; DO NOT EDIT.

func generatedCodexResponsesTargetConfigs() map[string]channelTargetConfig {
	return map[string]channelTargetConfig{
		"deepseek":       channelTargetConfig{ModelMapping: map[string]string{"codex": "deepseek-flash", "gpt": "deepseek-v4-pro", "mini": "deepseek-flash"}, ReasoningMapping: map[string]string{"gpt": "max"}, ReasoningParamStyle: "reasoning", NoVisionModels: []string{"deepseek-v4-pro"}, CodexToolCompat: boolRef(false), StripCodexClientTools: boolRef(false)},
		"mimo":           channelTargetConfig{ModelMapping: map[string]string{"codex": "mimo-v2.5-pro", "gpt": "mimo-v2.5-pro", "mini": "mimo-v2.5-pro"}, ReasoningMapping: map[string]string{"codex": "high", "gpt": "high", "mimo-v2.5": "high", "mini": "high"}, ServiceType: "responses", ReasoningParamStyle: "reasoning", NoVisionModels: []string{"mimo-v2.5-pro"}, VisionFallbackModel: "mimo-v2.5", CodexToolCompat: boolRef(true), StripCodexClientTools: boolRef(true), RateLimitRPM: 80},
		"compshare":      channelTargetConfig{ModelMapping: map[string]string{"codex": "deepseek-v4-flash", "gpt": "glm-5.2", "mini": "deepseek-v4-flash"}, ReasoningMapping: map[string]string{"MiniMax-M2.7": "xhigh", "gpt": "max", "mini": "high"}, ReasoningParamStyle: "reasoning", NoVisionModels: []string{"glm-5.2", "deepseek-v4-flash"}, VisionFallbackModel: "MiniMax-M2.7", CodexToolCompat: boolRef(false), StripCodexClientTools: boolRef(false)},
		"runapi":         channelTargetConfig{CodexToolCompat: boolRef(false), StripCodexClientTools: boolRef(false)},
		"unity2":         channelTargetConfig{CodexToolCompat: boolRef(false), StripCodexClientTools: boolRef(false)},
		"minimax":        channelTargetConfig{ModelMapping: map[string]string{"codex": "MiniMax-M2.7", "gpt": "MiniMax-M3", "mini": "MiniMax-M2.7"}, CodexToolCompat: boolRef(false), StripCodexClientTools: boolRef(false)},
		"dashscope":      channelTargetConfig{ModelMapping: map[string]string{"codex": "deepseek-v4-flash", "gpt": "deepseek-v4-pro", "mini": "deepseek-v4-flash"}, ReasoningMapping: map[string]string{"gpt": "max"}},
		"opencode-zen":   channelTargetConfig{ModelMapping: map[string]string{"codex": "deepseek-v4-flash", "gpt": "glm-5.2", "mini": "deepseek-v4-flash"}, ReasoningMapping: map[string]string{"codex": "high", "gpt": "max", "mini": "high"}, ReasoningParamStyle: "reasoning", NoVisionModels: []string{"glm-5.2", "deepseek-v4-flash"}, VisionFallbackModel: "minimax-m3"},
		"opencode-go":    channelTargetConfig{ModelMapping: map[string]string{"codex": "deepseek-v4-flash", "gpt": "glm-5.2", "mini": "deepseek-v4-flash"}, ReasoningMapping: map[string]string{"codex": "high", "gpt": "max", "mini": "high"}, ReasoningParamStyle: "reasoning", NoVisionModels: []string{"glm-5.2", "deepseek-v4-flash"}, VisionFallbackModel: "minimax-m3"},
		"kimi":           channelTargetConfig{ModelMapping: map[string]string{"codex": "kimi-k2.7", "gpt": "kimi-k2.7"}},
		"glm":            channelTargetConfig{ModelMapping: map[string]string{"codex": "glm-5.2", "gpt": "glm-5.2"}},
		"sensenova":      channelTargetConfig{ModelMapping: map[string]string{"codex": "deepseek-v4-flash", "gpt": "glm-5.2", "mini": "deepseek-v4-flash"}, NoVisionModels: []string{"glm-5.2", "deepseek-v4-flash"}, VisionFallbackModel: "sensenova-6.7-flash-lite"},
		"openrouter":     channelTargetConfig{CodexToolCompat: boolRef(false), StripCodexClientTools: boolRef(false)},
		"modelscope":     channelTargetConfig{ModelMapping: map[string]string{"codex": "deepseek-ai/DeepSeek-V4-Flash", "gpt": "ZhipuAI/GLM-5.2", "mini": "deepseek-ai/DeepSeek-V4-Flash"}, CodexToolCompat: boolRef(false), StripCodexClientTools: boolRef(false)},
		"volc-ark":       channelTargetConfig{ModelMapping: map[string]string{"codex": "deepseek-v4-flash", "gpt": "glm-5.3", "mini": "deepseek-v4-flash"}, ReasoningMapping: map[string]string{"codex": "high", "gpt": "max", "mini": "high", "minimax-m3": "xhigh"}, ReasoningParamStyle: "reasoning", NoVisionModels: []string{"glm-5.3", "deepseek-v4-flash"}, VisionFallbackModel: "minimax-m3", CodexToolCompat: boolRef(false), StripCodexClientTools: boolRef(false)},
		"qianfan":        channelTargetConfig{ModelMapping: map[string]string{"codex": "qianfan-code-latest", "gpt": "qianfan-code-latest", "mini": "qianfan-code-latest"}},
		"xfyun":          channelTargetConfig{ModelMapping: map[string]string{"codex": "astron-code-latest", "gpt": "astron-code-latest", "mini": "astron-code-latest"}, ServiceType: "responses"},
		"github-copilot": channelTargetConfig{ServiceType: "copilot", CodexToolCompat: boolRef(false), StripCodexClientTools: boolRef(false)},
		"atomgit":        channelTargetConfig{ModelMapping: map[string]string{"codex": "glm-5.2-200k", "gpt": "glm-5.2-200k", "mini": "glm-5.2-200k"}, ReasoningMapping: map[string]string{"codex": "high", "gpt": "high", "mini": "high"}, ServiceType: "openai", ReasoningParamStyle: "thinking", NoVisionModels: []string{"glm-5.2-200k"}, CodexToolCompat: boolRef(true), StripCodexClientTools: boolRef(true)},
	}
}
