version: '3'

includes:
  common: ./build/Taskfile.yml
  windows: ./build/windows/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml
  linux: ./build/linux/Taskfile.yml

vars:
  APP_NAME: "ccx-desktop"
  BIN_DIR: "bin"
  VITE_PORT: '{{.WAILS_VITE_PORT | default 3677}}'

tasks:
  build:
    summary: Builds the application
    cmds:
      - task: "{{OS}}:build"

  build:dev:
    summary: Builds the development application shell without rebuilding frontend assets
    cmds:
      - task: "{{OS}}:build:dev"

  package:
    summary: Packages a production build of the application
    cmds:
      - task: "{{OS}}:package"

  run:
    summary: Runs the application
    cmds:
      - task: "{{OS}}:run"

  run:embedded:
    summary: Runs the application with embedded frontend assets
    env:
      FRONTEND_DEVSERVER_URL: ""
    cmds:
      - task: "{{OS}}:run"

  dev:
    summary: Builds the frontend and runs the embedded desktop shell in development mode
    cmds:
      - task: common:build:frontend
        vars:
          BUILD_FLAGS: '-buildvcs=false -gcflags=all="-l" -ldflags="-X main.Version=dev -X main.BuildTime=unknown -X main.GitCommit=unknown"'
          PRODUCTION: "false"
      - task: build:dev
      - task: run:embedded
